version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    reviewers:
      - "johannesjahn"
    schedule:
      interval: "daily"
    groups:
      any:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch
